# Generated by Django 5.2.7 on 2025-12-18 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Proveedor',
                'verbose_name_plural': 'Categorías de Proveedores',
                'db_table': 'categoria_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('nombre_contacto', models.CharField(max_length=200, verbose_name='Nombre de contacto')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción del negocio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proveedores/', verbose_name='Logo/Foto')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='proveedores/fotos/')),
                ('pais', models.CharField(blank=True, choices=[('', 'Selecciona un país'), ('CL', 'Chile')], max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_mensajes', models.BooleanField(default=True)),
                ('notif_pedidos', models.BooleanField(default=True)),
                ('idioma', models.CharField(default='es', max_length=5)),
                ('zona_horaria', models.CharField(default='America/Santiago', max_length=50)),
                ('perfil_publico', models.BooleanField(default=True)),
                ('mostrar_estadisticas', models.BooleanField(default=True)),
                ('cobertura', models.CharField(choices=[('local', 'Local'), ('comunal', 'Comunal'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], default='local', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('contactos_enviados', models.PositiveIntegerField(default=0)),
                ('contactos_aceptados', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='proveedores', to='proveedor.categoriaproveedor', verbose_name='Rubros que oferta')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'promocion',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_servicios', to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'producto_servicio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'solicitud_contacto',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
