# Generated by Django 5.2.7 on 2025-12-18 20:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comerciante',
            name='region',
            field=models.CharField(choices=[('RM', 'Región Metropolitana'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('VI', 'Región del Libertador General Bernardo O’Higgins'), ('VII', 'Región del Maule'), ('VIII', 'Región del Biobío'), ('IX', 'Región de La Araucanía'), ('X', 'Región de Los Lagos'), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Región de Magallanes y de la Antártica Chilena'), ('XIII', 'Región de Ñuble'), ('XIV', 'Región de Los Ríos')], default='RM', help_text='Seleccione su región', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='categoria',
            field=models.CharField(choices=[('DESCUENTO', 'Descuento y Ofertas'), ('SORTEO', 'Sorteos y Rifas'), ('CAPACITACION', 'Capacitación y Cursos'), ('ACCESO', 'Acceso Exclusivo'), ('EVENTO', 'Eventos Especiales')], default='DESCUENTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='beneficios_fotos/'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_dados', to='usuarios.comerciante'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.post'),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='es_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='nombre_negocio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='rol',
            field=models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('ADMIN', 'Administrador'), ('PROVEEDOR', 'Proveedor'), ('TECNICO', 'Técnico de soporte')], default='COMERCIANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="El formato debe ser '+569XXXXXXXX'.", regex='^\\+569\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DUDA', 'Duda / Pregunta'), ('OPINION', 'Opinión / Debate'), ('RECOMENDACION', 'Recomendación'), ('NOTICIA', 'Noticia del Sector'), ('GENERAL', 'General'), ('NOTICIAS_CA', 'Noticias Club Almacén'), ('DESPACHOS', 'Despachos realizados'), ('NUEVOS_SOCIOS', 'Nuevos socios'), ('ACTIVIDADES', 'Actividades en curso')], default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='usuarios.comerciante'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='rubros_ofertados',
            field=models.CharField(help_text='Separados por coma', max_length=255),
        ),
    ]
